<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <AssemblyName>EngineEditor</AssemblyName>
    <RootNamespace>EngineEditor</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\scripts\EngineManagedApi.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Camera2D.cs" />
    <Compile Remove="Debug.cs" />
    <Compile Remove="DebugDraw.cs" />
    <Compile Remove="EntityManager.cs" />
    <Compile Remove="Input.cs" />
    <Compile Remove="ImGuizmo.cs" />
  </ItemGroup>
</Project>
